NBE_TARGET ?= native
export NBE_TARGET
NBE_OUTPUT = $(NBE_ROOT)/$(NBE_TARGET)
export NBE_OUTPUT

NBE_APPPATH ?= $(NBE_OUTPUT)/bin
export NBE_APPPATH
NBE_KMODPATH ?= $(NBE_OUTPUT)/kmod
export NBE_KMODPATH
NBE_LIBPATH ?= $(NBE_OUTPUT)/lib
export NBE_LIBPATH
NBE_INCPATH ?= $(NBE_OUTPUT)/include
export NBE_INCPATH
NBE_DBGPATH ?= $(NBE_OUTPUT)/debug
export NBE_DBGPATH
NBE_COVPATH ?= $(NBE_OUTPUT)/cov
export NBE_COVPATH

NBE_MK_INCPATH ?= $(NBE_OUTPUT)/_mkinc
export NBE_MK_INCPATH
NBE_MK_OBJPATH ?= $(NBE_OUTPUT)/_obj
export NBE_MK_OBJPATH
NBE_MK_KBUILDPATH ?= $(NBE_OUTPUT)/_kbuilt
export NBE_MK_KBUILDPATH
NBE_MK_LOBJPATH ?= $(NBE_OUTPUT)/_libobj
export NBE_MK_LOBJPATH
NBE_MK_COVPATH ?= $(NBE_OUTPUT)/_mkcov
export NBE_MK_COVPATH